# Generated by Django 5.1.5 on 2025-01-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anomalies",
            fields=[
                ("anomaly_id", models.AutoField(primary_key=True, serialize=False)),
                ("anomaly_type", models.CharField(max_length=19)),
                ("detected_at", models.DateTimeField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Anomalies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerClv",
            fields=[
                ("clv_id", models.AutoField(primary_key=True, serialize=False)),
                ("lifetime_value", models.JSONField()),
                ("last_purchase_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Customer_CLV",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("age", models.JSONField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=6, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "loyalty_status",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Customers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerSegments",
            fields=[
                ("segment_id", models.AutoField(primary_key=True, serialize=False)),
                ("segment_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("customer_count", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Customer_Segments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EsgScores",
            fields=[
                ("esg_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "environmental_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "social_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "governance_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_esg_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("recommendations", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ESG_Scores",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalTrends",
            fields=[
                ("trend_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.TextField()),
                ("total_sales", models.JSONField()),
                (
                    "top_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("campaign_performance", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Historical_Trends",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("stock_quantity", models.JSONField(blank=True, null=True)),
                ("reorder_level", models.JSONField(blank=True, null=True)),
                ("price", models.JSONField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Returns",
            fields=[
                ("return_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.JSONField()),
                ("refund_amount", models.JSONField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("return_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Returns",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                ("revenue_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("gross_revenue", models.JSONField()),
                ("net_revenue", models.JSONField()),
                ("discounts_applied", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Revenue",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SalesForecasts",
            fields=[
                ("forecast_id", models.AutoField(primary_key=True, serialize=False)),
                ("forecast_period", models.CharField(max_length=20)),
                ("predicted_sales", models.JSONField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Sales_Forecasts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                ("sentiment_id", models.AutoField(primary_key=True, serialize=False)),
                ("total_reviews", models.JSONField()),
                ("positive_reviews", models.JSONField()),
                ("neutral_reviews", models.JSONField()),
                ("negative_reviews", models.JSONField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Sentiment_Analysis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockForecasts",
            fields=[
                (
                    "stock_forecast_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("forecasted_demand", models.JSONField()),
                (
                    "restock_recommendation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Stock_Forecasts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Suppliers",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("supplier_name", models.CharField(max_length=100)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Suppliers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.JSONField()),
                ("unit_price", models.JSONField()),
                ("total_amount", models.JSONField()),
                ("transaction_date", models.DateTimeField(blank=True, null=True)),
                ("payment_method", models.CharField(max_length=6)),
            ],
            options={
                "db_table": "Transactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "companyname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Users",
                "managed": False,
            },
        ),
    ]
